Fix log density spline extrapolation
theochem/AtomDB pull request #133
Opened 2024-12-08 05:05 UTC by msricher

2024-12-10 16:09 UTC, PaulWAyers requested changes
Can you add some comments on what the code is doing, and how it is resolving the issue? My understanding is that you clip the vector, and then "fix" the NaN's later.

I think like 191 is just fixing a different bug.

I'm not sure what 195 is doing.

2024-12-11 12:58 UTC, PaulWAyers approved these changes
Looks good to me. @marco-2023 and/or @gabrielasd ?

2024-12-16 16:59 UTC, marco-2023 commented on atomdb/species.py
> +            np.log(y.clip(min=np.finfo(float).eps ** 2)) if log else y,
@PaulWAyers and @msricher  I have a doubt, for all the features that we describe as splines, for values of `r` outside our array of values, the spline is a polynomial that will diverge for $r \to \infty$. If we know the correct decay for some of the features, why not use a switch function (like hyperbolic tangent) to change between the spline and the function (or even a constant value) outside its range?

2024-12-16 17:47 UTC, marco-2023 approved these changes

2024-12-17 15:27 UTC, merged