Separate dependencies
theochem/AtomDB pull request #53
Opened 2024-03-27 06:58 UTC by marco-2023

Here I separate the developer tests from the use tests and make the developer dependencies optional through the code. @msricher please feel confident to modify anything you see that can be improved. I am not as familiar with this package as you are so you have a clearer vision of what is needed.

This PR is an attempt to solve #52 

@gabrielasd this PR does not include the latest changes you made to the API.

2024-03-27 13:47 UTC, msricher requested changes

2024-03-27 13:47 UTC, msricher commented on .github/workflows/pytest.yaml
I think you should only need to do (for example) `pip install ".[dev]"`, and then list the optional dev dependencies in the pyproject.toml file.  This way everything is tracked in pyproject.toml. Dependencies shouldn't have to be manually installed.

See https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

2024-03-27 13:47 UTC, msricher commented on atomdb/utils.py
There's no need for such a function "dev_method". The datasets/* submodules are never imported directly.  Just wrap the stuff in api.py (accessing the docstring, compiling a species file) in a try/except.  This seems pointless.

2024-04-01 05:24 UTC, marco-2023 commented
I will close this as the functionality wanted is achieved in #57

2024-04-01 05:24 UTC, closed without merging